#lexik_jwt_authentication:
#    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
#    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
#    pass_phrase:      ':rHooA4n3nqQ' # required for token creation, usage of an environment variable is recommended
#    token_ttl:        3600

lexik_jwt_authentication:
    secret_key:       '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key:       '%env(resolve:JWT_PUBLIC_KEY)%'  # required for token verification
    pass_phrase:      '%env(resolve:JWT_PASSPHRASE)%' # required for token creation, usage of an environment variable is recommended
    token_ttl:        31536000