vich_uploader:
    db_driver: orm

    mappings:
        facturation_file:
            uri_prefix: /uploads/factures
            upload_destination: '%kernel.project_dir%/public/uploads/factures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
